version: '3.8'

services:
  # PHP-FPM Service (for Laravel)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    networks:
      - app-network

  # Nginx Service
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/html
      - ./frontend/out:/var/www/frontend
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  # MySQL Database Service
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: vibe_app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  # Node.js Service (for Next.js development/build)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules # Anonymous volume to prevent host node_modules from overwriting container's
    ports:
      - "3000:3000"
    networks:
      - app-network
    command: npm run dev # Or npm run build && npm run start for production

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
